version: "1.0"
name: CompanyRag CI
displayName: CompanyRag CI
stages:
- name: Build and Test
  displayName: Build and Test
  strategy: naturally
  trigger: auto
  steps:
  - step: build@maven
    name: Maven Build
    displayName: Maven 构建
    jdkVersion: "17"
    mavenVersion: 3.6.3
    commands:
    - mvn clean package -B -Dtest='!@IntegrationTest' -Dsurefire.failIfNoSpecifiedTests=false
    artifacts:
    - name: BUILD_ARTIFACT
      path:
      - ./company-rag-bootstrap/target/*.jar
      type: .tar.gz
    settings: []
    caches:
    - "~/.m2"
    strategy:
      retry: "0"
      resource:
        cpu: "2"
        memory: "4"