version: "1.0"
name: CompanyRag CI
displayName: CompanyRag 持续集成流水线
stages:
- name: Maven 构建与测试
  displayName: Maven 构建与测试
  strategy: naturally
  trigger: auto
  steps:
  - step: build@maven
    name: maven-build
    displayName: Maven 构建
    jdkVersion: "17"
    mavenVersion: 3.9.9
    commands:
    - mvn clean package -B -DexcludedGroups=integration-test -Dsurefire.failIfNoSpecifiedTests=false
    artifacts:
    - name: BUILD_ARTIFACT
      path:
      - ./company-rag-bootstrap/target/*.jar
      type: .tar.gz
- name: Docker 镜像构建
  displayName: Docker 镜像构建
  strategy: naturally
  trigger: auto
  steps:
  - step: build@docker
    name: build-docker-example
    displayName: 镜像构建
    type: account
    repository: hub.gitee.com
    username: LongHuDaoChang
    password: 33b59a1f781682e426be8fe3606b40ff
    tag: "${GITEE_PIPELINE_BUILD_NUMBER}"
    dockerfile: ./Dockerfile
    context: ""
    artifacts: []
    isCache: false
    processorType:
    - amd64
    parameter: {}
    strategy:
      retry: "0"
    outParamsAlias:
      GITEE_DOCKER_IMAGE: GITEE_DOCKER_IMAGE_0
triggers:
  trigger: auto
  push:
    branches:
      prefix:
      - main
      precise: []
      include: []
notify: []
