version: "1.0"
name: CompanyRag CI
displayName: CompanyRag CI
stages:
- name: Build and Test
  displayName: Build and Test
  strategy: naturally
  trigger: auto
  steps:
  - step: build@maven
    name: 6b4fd096
    displayName: Maven 构建
    jdkVersion: "17"
    mavenVersion: 3.3.9
    commands:
    - mvn clean package -B
    artifacts:
    - name: BUILD_ARTIFACT
      path:
      - ./target
      type: .tar.gz
    settings: []
    caches:
    - "~/.m2"
    strategy:
      retry: "0"
      resource:
        cpu: "2"
        memory: "4"
- name: Docker Build
  displayName: Docker Build
  strategy: naturally
  trigger: auto
  steps:
  - step: build@docker
    name: Docker Build
    displayName: Docker 镜像构建
    repository: "{{CERTIFICATION.${CERTIFICATE}.server}}"
    username: "{{CERTIFICATION.${CERTIFICATE}.username}}"
    password: "{{CERTIFICATION.${CERTIFICATE}.password}}"
    dockerfile: ./Dockerfile
triggers:
  trigger: auto
  push:
    branches:
      prefix:
      - main
      precise: []
      include: []
notify: []
